Repository sofrel-group14/decide, pull requests merged in 2021-02, with the labels that each got.

#50 Issue 40 quadrant axes point fix
  src/main/java/Point.java
  src/test/java/PointTest.java
Labels: bug

#51 Implement LIC5 with Unit Test
  src/main/java/CMV.java
  src/test/java/CMVTest.java
  src/test/java/LIC5Test.java
Labels: enhancement

#34 Implement LIC 8
  src/main/java/CMV.java
  src/main/java/Point.java
  src/test/java/LIC8Test.java
  src/test/java/PointTest.java
Labels: enhancement

#53 Implement LIC14
  src/main/java/CMV.java
  src/test/java/CMVTest.java
  src/test/java/LIC14Test.java
Labels: enhancement

#33 Implement LIC6 with test cases
  .idea/codeStyles/codeStyleConfig.xml
  src/main/java/CMV.java
  src/main/java/Point.java
  src/test/java/LIC6Test.java
Labels: enhancement

#5 Improve README
  README.md
Labels: documentation

#59 Implement LIC 13
  .gitignore
  src/main/java/CMV.java
  src/main/java/Point.java
  src/test/java/LIC13Test.java
  src/test/java/PointTest.java
Labels: enhancement
